project:
  type: book
  output-dir: ../_build/book

book:
  title: "Computational Geodynamics Primer"
  author:
    - "Louis Moresi"
  date: today
  bread-crumbs: True
  chapters:
    - part: "Preface"
      chapters:
        - index.qmd
        - intro.qmd

    # Core content - to be organized
    - part: "**Part I: Mathematical Fundamentals**"
      chapters:
        - Part1-Fundamentals/placeholder.qmd

    - part: "**Part II: Fluid Dynamics**"
      chapters:
        - Part2-FluidDynamics/placeholder.qmd
        - Part2-FluidDynamics/inviscid-flows.qmd

    - part: "**Part III: Geodynamics**"
      chapters:
        - Part3-Geodynamics/placeholder.qmd

    - part: "**Part IV: Numerical Methods**"
      chapters:
        - Part4-NumericalMethods/placeholder.qmd

    - part: "**Part V: Computational Exercises**"
      chapters:
        - Part5-Computational/placeholder.qmd
        - Part5-Computational/Benchmarks/analytical-solutions.qmd

    # Draft material - Geodynamics
    - part: "**Draft: Geodynamics**"
      chapters:
        - DraftMaterial/ContinuumMechanics.qmd
        - DraftMaterial/NavierStokes.qmd
        - DraftMaterial/MantleDynamics.qmd
        - DraftMaterial/StokesFlowApplications.qmd
        - DraftMaterial/ThermalConvection.qmd
        - DraftMaterial/LithosphericDynamics.qmd

    # Draft material - Computational Methods
    - part: "**Draft: Computational Methods**"
      chapters:
        - DraftMaterial/NumericalMethods1.qmd
        - DraftMaterial/NumericalMethods2.qmd
        - DraftMaterial/NumericalMethods3.qmd
        - DraftMaterial/NumericalMethods4.qmd
        - DraftMaterial/NumericalMethods5.qmd

    # References
    - part: "References"
      chapters:
        - summary.qmd
        - references.qmd

    # Contributions
    - part: "Contributing"
      chapters:
        - Contributions/contributing.qmd
        - Contributions/style-guide.qmd
        - Contributions/example-citations.qmd

  # Uncomment when you add slides
  # - part: "Slides"
  #   chapters:
  #     - LectureSlides/Lecture1.qmd

  appendices:
    - Notebooks/BinderLandingPage.qmd
    - Notebooks/TestNB1.ipynb
    - Notebooks/TestQMD_NB1.qmd

  navbar:
    search: true
    logo: assets/ANU-logo.png
    background: "#C58812"  # ANU honey colour
    foreground: white
    left:
      - text: "Introduction"
        href: index.qmd
      - text: "Details"
        href: summary.qmd
      - text: "Slides"
        href: LectureSlides/Lecture1.qmd
    right:
      - icon: github
        href: https://github.com/ANU-RSES-Education/Computational-Geodynamics-Primer
        aria-label: GitHub

  sidebar:
    logo: assets/AuWorldEQ.jpg
    style: "docked"
    background: light

bibliography: references.bib

execute:
  enabled: false

format:
  live-html:
    theme: [cosmo, "assets/theme.scss"]
    css: assets/styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-fold: false
    linkcolor: "#C58812"
    number-sections: false
    number-depth: 1
    # Math rendering
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            tex: {
              tags: 'ams',
              packages: {'[+]': ['ams', 'amsmath', 'amssymb', 'color', 'newcommand', 'boldsymbol']},
              inlineMath: [['$', '$'], ['\\(', '\\)']],
              displayMath: [['$$', '$$'], ['\\[', '\\]']],
              macros: {
                dGamma: "{\\mathbf{d}\\boldsymbol{\\Gamma}}",
                uv: "{\\mathbf{u}}",
                vv: "{\\mathbf{v}}",
                DIV: "{\\nabla\\cdot}",
                GRAD: "{\\nabla}",
                CURL: "{\\nabla\\times}"
              }
            }
          };
          </script>

    # code-links:
    #   - text: Open in Binder
    #     icon: rocket-takeoff
    #     href: https://mybinder.org/v2/gh/ANU-RSES-Education/EMSC-QuartoBook/HEAD?labpath=WebBook/Notebooks%2FBinderLandingPage.qmd

    other-links:
      - text: Github Repository
        icon: github
        href: https://github.com/ANU-RSES-Education/Computational-Geodynamics-Primer

  # pdf:
  #   documentclass: scrreprt

pyodide:
  packages:
    - micropip
    - netcdf4
    - xarray
    - pydap
    - jinja2
    - ssl
    - owslib
